version: '3'
services:
  python-container:
    build:
      context: .
      dockerfile: container-python.dockerfile
    ports:
      - 8001:5000
    volumes:
      - ./srcPython:/app
  java-container:
    build:
      context: .
      dockerfile: container-java.dockerfile
    ports:
      - 8002:8080